-- ENUM Types
CREATE TYPE health_status_enum AS ENUM ('good', 'normal', 'bad', 'very_bad');
CREATE TYPE phys_sym_status_enum AS ENUM ('mild', 'moderate', 'severe');

-- Tables
CREATE TABLE "question" (
  "question_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "question_text" VARCHAR
);

CREATE TABLE "answer" (
  "answer_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "question_id" INT,
  "answer_text" VARCHAR,
  CONSTRAINT fk_question FOREIGN KEY ("question_id") REFERENCES "question" ("question_id")
);

CREATE TABLE "user" (
  "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_name" VARCHAR
);

CREATE TABLE "user_question" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" INT,
  "question_id" INT,
  "enabled" BOOLEAN,
  CONSTRAINT fk_user FOREIGN KEY ("user_id") REFERENCES "user" ("user_id"),
  CONSTRAINT fk_question FOREIGN KEY ("question_id") REFERENCES "question" ("question_id")
);

CREATE TABLE "response" (
  "response_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" INT,
  "response_date" DATE,
  "answer_id" INT,
  "question_id" INT,
  CONSTRAINT fk_user FOREIGN KEY ("user_id") REFERENCES "user" ("user_id"),
  CONSTRAINT fk_question FOREIGN KEY ("question_id") REFERENCES "question" ("question_id"),
  CONSTRAINT fk_answer FOREIGN KEY ("answer_id") REFERENCES "answer" ("answer_id")
);

CREATE TABLE "daily_phys" (
  "daily_phys_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" INT,
  "entry_date" DATE,
  "height_cm" FLOAT,
  "weight_kg" FLOAT,
  "hours_slept" FLOAT,
  "health_status_id" INT,
  CONSTRAINT fk_user FOREIGN KEY ("user_id") REFERENCES "user" ("user_id")
);

CREATE TABLE "health_status" (
  "health_status_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" INT,
  "status" health_status_enum,
  "entry_date" DATE,
  CONSTRAINT fk_user FOREIGN KEY ("user_id") REFERENCES "user" ("user_id")
);

CREATE TABLE "phys_sym" (
  "phys_sym_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "symptom_name" VARCHAR
);

CREATE TABLE "phys_sym_status" (
  "phys_sym_status_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "phys_sym_status" phys_sym_status_enum
);

CREATE TABLE "user_symptoms" (
  "user_symptom_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" INT,
  "entry_date" DATE,
  "phys_sym_id" INT,
  "phys_sym_status_id" INT,
  CONSTRAINT fk_user FOREIGN KEY ("user_id") REFERENCES "user" ("user_id"),
  CONSTRAINT fk_symptom FOREIGN KEY ("phys_sym_id") REFERENCES "phys_sym" ("phys_sym_id"),
  CONSTRAINT fk_symptom_status FOREIGN KEY ("phys_sym_status_id") REFERENCES "phys_sym_status" ("phys_sym_status_id")
);

CREATE TABLE "api_data" (
  "api_data_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "api_data_date" DATE,
  "response_id" INT,
  CONSTRAINT fk_response FOREIGN KEY ("response_id") REFERENCES "response" ("response_id")
);