CREATE DATABASE "the_luna_project";

\c "the_luna_project";

-- Tables
CREATE TABLE "question" (
  "question_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "question_text" VARCHAR,
  "container_type" VARCHAR
);

CREATE TABLE "answer" (
  "answer_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "question_id" INT,
  "answer_text" VARCHAR,
  "button_type" VARCHAR,
  "button_style" VARCHAR,
  CONSTRAINT fk_question FOREIGN KEY ("question_id") REFERENCES "question" ("question_id")
);

CREATE TABLE "user_account" (
  "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_name" VARCHAR,
  "child_name" TEXT,
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "user_question" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" INT,
  "question_id" INT,
  "enabled" BOOLEAN,
  CONSTRAINT fk_user FOREIGN KEY ("user_id") REFERENCES "user_account" ("user_id"),
  CONSTRAINT fk_question FOREIGN KEY ("question_id") REFERENCES "question" ("question_id")
);

CREATE TABLE "response" (
  "response_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" INT,
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "answer_id" INT,
  "question_id" INT,
  CONSTRAINT fk_user FOREIGN KEY ("user_id") REFERENCES "user_account" ("user_id"),
  CONSTRAINT fk_question FOREIGN KEY ("question_id") REFERENCES "question" ("question_id"),
  CONSTRAINT fk_answer FOREIGN KEY ("answer_id") REFERENCES "answer" ("answer_id")
);

CREATE TABLE "daily_phys" (
  "daily_phys_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" INT,
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "height_cm" FLOAT,
  "weight_kg" FLOAT,
  "hours_slept" FLOAT,
  "condition_scale" INT,
  CONSTRAINT fk_user FOREIGN KEY ("user_id") REFERENCES "user_account" ("user_id")
);

CREATE TABLE "phys_sym" (
  "phys_sym_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "symptom_name" VARCHAR
);

CREATE TABLE "user_symptoms" (
  "user_symptom_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" INT,
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "phys_sym_id" INT,
  "severity_scale" INT,
  CONSTRAINT fk_user FOREIGN KEY ("user_id") REFERENCES "user_account" ("user_id"),
  CONSTRAINT fk_symptom FOREIGN KEY ("phys_sym_id") REFERENCES "phys_sym" ("phys_sym_id")
);

CREATE TABLE "api_data" (
  "api_data_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "response_id" INT,
  CONSTRAINT fk_response FOREIGN KEY ("response_id") REFERENCES "response" ("response_id")
);

-- \i C:/Users/rober/Desktop/projects/the-luna-project/src/lib/psql-migration/librarytablepopulation.sql
